export const inputs = {
  category: "",
  contact: "",
  employmentType: "Self-employed business",
  yearlyIncome: 0,
  monthlyIncome: 0,
  bank: "",
  employerName: "",
  employerType: "",
  loanAmount: "",
  loanTenure: "",
  name: "",
  email: "",
  gender: "",
  dateOfBirth: "",
  panCardNum: "",
  state: "",
  city: "",
  pincode: "",
  residencyType: "Owned by self/spouse",
  incomeReceivedAs: "",
  existingEmi: 0,
  loanStartDate: "",
  primaryBankAccount: "",
  // business
  profession: "",
  registrationNumber:"",
  businessPlaceOwnershipType:"",
  currentBusinessState:"",
  currentBusinessCity: "",
  currentBusinessPincode:"",
  yearsInCurrentBusiness: "",
  YearsInBusinessOver5:6,
  compnayType: "",
  businessNature: "",
  subIndustryType: "",
  industryType: "",
  companyStartDate: "",
  currentYearTurnOver: "",
  previousYearTurnOver: "",
  currentYearNetProfit:"",
  previousYearNetProfit:"",
  collateralOption: "",
  otherCollateralOptionType:"",
  // property
  newPropertyType: "single-family home",
  newHouseNumber: "",
  newPropertyLocality: "",
  newPropertyCity: "",
  newPropertyState: "",
  newPropertyPincode: "",
  // vehicle
  carManufacturer: "",
  carModel: "",
  manufacturingYear: "",
  vehicleVIN: "",
  // education
  fieldOfStudy: "",
  universityName: "",
  instituteName: "",
  enrollmentStatus: "",
  courseDuration: "",
  educationCost: "",
  // project loan
  projectDescription: "",
  projectObjective: "",
  scopeOfWorkandDeliverables: "",
  projectBudget: "",
  projectStartDate: "",
  expectedDateOfComletion: "",
};
