export const residencyType = [
  "Owned by self/spouse",
  "Owned by parents/siblings",
  "Rented with family",
  "Rent and stay alone",
  "Paying Guest/Hostel",
  "Company Provided",
];

export const existingWokringCapitalLoanTypes = [
  "Personal loan",
  "Business loan",
  "Home loan",
  "Car loan",
  "Working Capital",
  "Project Loan",
  "OD/CC",
  "Loan against share",
  "Gold loan",
  "Other",
];

export const employmentTypes = [
  "Salaried",
  "Self-employed business",
  "Self-employed professional",
];

export const businessLoanEmploymentTypes = [
  "Self-employed business",
  "Self-employed professional",
];

export const primaryBankAccountOptions = [
  "HDFC",
  "SBI",
  "Bank Of India",
  "ICICI",
  "Punjab National Bank",
  "Kotak Mahindra Bank",
  "AXIS",
  "Citibank",
  "Other",
];

export const incomeRecievedAs = [
  "Cash",
  "Cheque",
  "Electronically deposited-IMPS",
  "Electronically deposited-NFT/RTGS",
];

export const yearsInCurrentBusiness = [
  "Under 1 years",
  "1-2 years",
  "2-3 years",
  "3-5 years",
  "over 5 years",
];

export const businessPlaceOwnershipTypeInputs = [
  "Owned",
  "Rented",
  "Lease",
  "Other",
];

export const businessCompanyTypes = [
  "Proprietorship",
  "Partnership Firm",
  "Privated Limited Company",
  "Public Limited Company",
  "Limited Liability Company",
  "Director Applying As An Individual",
  "Other",
];

export const primaryBankAccount = [
  "HDFC",
  "SBI",
  "Bank Of India",
  "ICICI",
  "Punjab National Bank",
  "Kotak Mahindra Bank",
  "AXIS",
  "Citibank",
  "Multiple transaction banks",
  "Other",
];

//salaried
export const employerTypes = [
  "Privated limited",
  "Limited",
  "Partnership",
  "Proprietorship",
  "Government",
  "Other",
];

export const businessNatureTypes = [
  "Manufacture",
  "Trader/Wholesaler",
  "Retailer",
  "Service Provider",
  "Other",
];

export const homeLoanPropertyTypes = ["New", "Under-construction", "Old-construction","Other"];

export const industryTypes = [
  "Agriculture",
  "Automobiles",
  "Cement",
  "Chemical",
  "Computer",
  "Construction",
  "Consumer Durables",
  "Container &  Packaging",
  "Durables",
  "Energy",
  "Food & Beverages",
  "Hardware Equipments",
  "Healthcare",
  "Household Products",
  "Industrial Projects",
  "Metals",
  "Paper",
  "Petroleum Products",
  "Plastic",
  "Rubber",
  "Textiles",
  "Other",
];

export const collateralOptionTypes = [
  "Residential Property",
  "Commercial Property",
  "Industrial Property",
  "Other",
];

export const projectTypes = [
  "Residential Property",
  "Commercial Property",
  "Industrial Property",
  "Other",
];

export const transmissionTypes = ["Diesel", "Petrol", "CNG", "Electric"];

export const BanksForCreditCards = [
  "State Bank of India (SBI)",
  "ICICI Bank",
  "HDFC Bank",
  "Axis Bank",
  "Kotak Mahindra Bank",
  "Standard Chartered Bank",
  "HSBC",
  "Citibank",
  "IDFC First Bank",
  "RBL Bank",
  "Yes Bank",
  "IndusInd Bank",
  "Bank of Baroda",
  "Punjab National Bank (PNB)",
  "Other",
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor (Timor-Leste)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const commercialPropertyTypes = ["Commercial", "Industrial", "Other"];

//////////////////////
/////////////////////////////////
// /////////////////

export const educationEnrollmentStatus = ["Full-time", "Part-time"];
